### ISSUE TITLE
Any plans for the next release?

### ISSUE THREAD

**Issue by fauno** [benbalter/jekyll-include-cache#19]
I was debugging why the site I'm working on wasn't caching includes until I noticed there were some changes on master, so I tried it and without changing the templates the build time went from 100 to 20 seconds and includes were being cached :)

**Comment by pdmosses** [comment]
As I'm experiencing the same issue as @fauno (and originally raised by @qwtel in #16) I would like to support the request for a release with the fix in #17.

I'm trying to improve the scalability of [Just the Docs](https://pmarsceill.github.io/just-the-docs/) for sites with large navigation panels. Locally building the theme docs together with regression tests currently takes [more than **600 seconds**](https://github.com/benbalter/jekyll-include-cache/files/5348606/include-cache-0.2.0.txt) using the current release (0.2.0) of this gem, whereas it takes just [**25 seconds**](https://github.com/benbalter/jekyll-include-cache/files/5348607/include-cache-master.txt) using the current master! (Jekyll 4.1.1 on macOS Catalina, MacBook Air (Retina, 13-inch, 2018), 1.6 GHz Dual-Core Intel Core i5, Memory 16 GB 2133 MHz LPDDR3)

This is the first time I've tried using this gem, and I know very little about Ruby and Jekyl, but I think the cause of the issue with 0.2.0 is that I'm passing arrays of pages as parameters to recursive inclusions of the file that creates the navigation links, and hashing the parameters is taking a long time (perhaps aggravated by GC). I could work around the issue (replacing the arrays of pages by arrays of their required fields) but #17 appears to address the root cause of the current inefficiency.

**Comment by benbalter** [comment]
[Released!](https://github.com/benbalter/jekyll-include-cache/releases/tag/v0.2.1)

**Comment by qwtel** [comment]
> currently takes [more than **600 seconds**](https://github.com/benbalter/jekyll-include-cache/files/5348606/include-cache-0.2.0.txt) using the current release (0.2.0) of this gem, whereas it takes just [**25 seconds**](https://github.com/benbalter/jekyll-include-cache/files/5348607/include-cache-master.txt) using the current master!

Those are some impressive gains! Glad it works so well 👍

**Comment by pdmosses** [comment]
@qwtel It turned out that the magnitude of the gains I reported was partly due to a page-dependent parameter (the navigation path to the page) which inhibited reuse of the cached navigation links. Nevertheless, getting the build time down was very helpful for debugging. After further analysis and optimisation, I've managed to get good cache reuse with larger navigation hierarchies.

@benbalter Many thanks for releasing v0.2.1 so quickly in response to my support for @fauno's request – much appreciated!
